### ISSUE TITLE
Unique IDs across files

### ISSUE THREAD

**Issue by pjarnfelt** [radiatoryang/merino#19] opened 2018-10-16 13:56 UTC
I seems like Merino v 0.5 is enforcing unique IDs across yarn files in a folder. 
A "-2" is added to a node on the node that has the same name in a different .yarn file.

**Comment by radiatoryang** [comment] 2018-10-16 14:54
Yes, because non-unique node titles will break Yarn Spinner when you playtest

What would you prefer / can you talk about why you'd need different behavior?

**Comment by radiatoryang** [comment] 2018-10-16 23:19
Make sure you click "Unload All" first, and then try loading just one file

The problem is that even if I disabled validation for unique node titles, it would still fail when Merino sends it in to Yarn Spinner to test. Merino assumes all the currently open files will be loaded in Yarn Spinner together... but you just want to be able to edit an entire folder, yet playtest each file separately in isolation?

I could add some sort of "Playtest Selected Nodes Only" button, which would send only the currently selected nodes to Yarn Spinner. Would that work for you?

**Comment by pjarnfelt** [comment] 2018-10-25 14:33
I did the Unload All, then only opened one file, but it still made the nodes unique (by adding -2). 
Maybe the others were still in memory somehow?

I think there could be a couple of use-cases.
1. accept uniqueness of nodes in opened files -> then it needs to ensure it won't mess with previously opened files; only have uniqueness of opened files.
2. have a setting for automatic uniqueness. -> If a node is not unique in the playtest and there is confusion, then it could perhaps give a warning.
3. uniqueness is only per yarn file -> Playtest are only per yarn file. 

I could work with any of these. But why would one have uniqueness across files? You load only one yarn file in a scene, right?

**Comment by radiatoryang** [comment] 2018-10-30 05:12
The Yarn Spinner "Space" example actually has you create a different Yarn file for each NPC, you can totally load more than one Yarn file at a time and it's part of the workflow! When you load them all, they get merged into the same network

The current functionality should be "accept uniqueness of nodes in opened files -> then it needs to ensure it won't mess with previously opened files; only have uniqueness of opened files" ALREADY though, so I guess the file list is not getting updated properly

Will take a look at this after the big v0.6 node map merge is done

**Comment by radiatoryang** [comment] 2019-02-02 17:46
closing the issue for now then!

**Closed by radiatoryang** 2019-02-02 17:46 UTC
Labels: bug
